In [1]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd

Get started: fluid data manipulation with Pandas.

In [113]:
datfile = pd.read_csv('DataFiles/car_fuel_efficiency.csv')

In [3]:
datfile

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

Print the first n rows of the dataset.

In [ ]:
datfile.head(n=4)
#Or datfile["num_cylinders"].head(n=5) if you want a specific column

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736

Print the last n rows of the dataset.

In [ ]:
datfile.tail(n=3)

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

Print some specific columns of the dataset.

In [ ]:
datfile[["num_cylinders", "horsepower", "num_doors"]].head()

   num_cylinders  horsepower  num_doors
0            3.0       159.0        0.0
1            5.0        97.0        0.0
2            NaN        78.0        0.0
3            4.0         NaN        2.0
4            1.0       140.0        2.0

Print the number of unique values in the "fuel_type" column.

In [ ]:
datfile["fuel_type"].value_counts().shape#.plot(kind="bar", figsize=(10, 5))

(2,)

Accessing specific elements in the DataFrame using iloc, as it was a numpy array, including column headers.

In [ ]:
datfile.iloc[1,2]

np.float64(97.0)

Here there are two ways to extract the NaN elements in the "num_cylinders" column of the dataset. The first one prints the whole rows where the "num_cylinders" column is NaN, while the second one prints only the NaN elements and their row indices.

In [ ]:
#datfile[datfile["num_cylinders"].isna()]
ncyl = pd.Series(datfile["num_cylinders"])
ncyl[ncyl.isna()].shape

(482, 11)

Now see how many NaN elements are for every column in the dataset. The output is a Series with the column names as indices and the number of NaN elements as values. datfile.isna() by itself only returns a DataFrame of the same shape as datfile, but with True or False values depending on whether the element is NaN or not. The sum() method then counts the number of True values for each column.

In [ ]:
nans = datfile.isna().sum()
nans[nans > 0]
#nans[nans > 0].size

num_cylinders    482
horsepower       708
acceleration     930
num_doors        502
dtype: int64

Get the values or copying them to a numpy array. Both methods are equivalent.

In [ ]:
datfile[["num_cylinders", "model_year", "origin"]].values
#(datfile.iloc[:, [1,5,6]]).to_numpy().copy()

array([[3.0, 2003, 'Europe'],
       [5.0, 2007, 'USA'],
       [nan, 2018, 'Europe'],
       ...,
       [2.0, 2008, 'USA'],
       [4.0, 2011, 'USA'],
       [3.0, 2005, 'Asia']], dtype=object)

Extract the rows corresponding to cars coming from Asia. From it extract the feature "fuel_efficiency_mpg", and then find its maximum.

In [ ]:
np.max(datfile[datfile["origin"]=="Asia"].fuel_efficiency_mpg)

23.759122836520497

Drop the NaN entries of a column and compute the average.

In [114]:
filtered_HP = datfile["horsepower"].dropna()
np.average(filtered_HP)

np.float64(149.65729212983547)

Extract the most frequent value and how many times it appears.

In [115]:
mstfreq = filtered_HP.value_counts().index[0]
filtered_HP.value_counts().head(n=1)

horsepower
152.0    142
Name: count, dtype: int64

Fill the missing values in the "horsepower" column with the most frequent value from the previous step.

In [116]:
datfile["horsepower"] = datfile["horsepower"].fillna(mstfreq)

In [117]:
datfile["horsepower"].value_counts().head(n=1)

horsepower
152.0    850
Name: count, dtype: int64

Compute again the average.

In [118]:
np.average(datfile["horsepower"].values)

np.float64(149.82821516900248)

From the rows corresponding to Asian cars, keep the columns "vehicle_weight" and "model_year".

In [130]:
asiancars = datfile[datfile["origin"]=="Asia"]
X = asiancars[["vehicle_weight", "model_year"]].head(n=7).values

In [133]:
Xm1 = np.linalg.inv(X.T @ X)
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
w = Xm1 @ X.T @ y
np.sum(w)

np.float64(0.5187709081074007)