This file is part of the homework 1 of the MLZoomCamp, cohort 2026. The homework .md file with the assignments is available here https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/main/cohorts/2026/homework/01-intro/homework.md

In [2]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd

<span style="color: orange">Q1. Check the pandas version.</span>
<span style="color: lightgreen">Ans.: 2.2.3</span>

In [3]:
pd.__version__

'2.2.3'

Get started: fluid data manipulation with Pandas.

In [3]:
datfile = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [6]:
datfile.head(n=6)
#Or datfile["num_cylinders"].head(n=5) if you want a specific column

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
5,2007,USA,Hybrid,Front-wheel drive,2,2290,6,266.0,4260,18.8,31.2

<span style="color: orange">Q2. How many records (rows) are in the dataset?</span>
<span style="color: lightgreen">Ans.: 10000</span>

In [7]:
datfile.shape

(10000, 11)

Print the last n rows of the dataset.

In [9]:
datfile.tail(n=3)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

Print some specific columns of the dataset.

In [ ]:
datfile[["num_cylinders", "horsepower", "num_doors"]].head()

   num_cylinders  horsepower  num_doors
0            3.0       159.0        0.0
1            5.0        97.0        0.0
2            NaN        78.0        0.0
3            4.0         NaN        2.0
4            1.0       140.0        2.0

<span style="color: orange">Q3. Print the number of unique values in the "fuel_type" column.</span>
<span style="color: lightgreen">Ans.: 3</span>

In [8]:
datfile["fuel_type"].value_counts().shape#.plot(kind="bar", figsize=(10, 5))

(3,)

Accessing specific elements in the DataFrame using iloc, as it was a numpy array, including column headers.

In [ ]:
datfile.iloc[1,2]

np.float64(97.0)

Now let us see how many NaN elements there are for every column in the dataset. The output is a Series with the column names as indices and the number of NaN elements as values. datfile.isna() by itself only returns a DataFrame of the same shape as datfile, but with True or False values depending on whether the element is NaN or not. The sum() method then counts the number of True values for each column.

<span style="color: orange">Q4. How many columns in the dataset have missing values?</span>

<span style="color: lightgreen">Ans.: 2. The horsepower and acceleration variables are the only ones with missing values.</span>

In [11]:
nans = datfile.isna().sum()
nans[nans > 0]
#nans[nans > 0].size

horsepower      877
acceleration    264
dtype: int64

Get the values or copying them to a numpy array. Both methods are equivalent.

In [ ]:
datfile[["num_cylinders", "model_year", "origin"]].values
#(datfile.iloc[:, [1,5,6]]).to_numpy().copy()

array([[3.0, 2003, 'Europe'],
       [5.0, 2007, 'USA'],
       [nan, 2018, 'Europe'],
       ...,
       [2.0, 2008, 'USA'],
       [4.0, 2011, 'USA'],
       [3.0, 2005, 'Asia']], dtype=object)

Extract the rows corresponding to cars coming from Asia. From it extract the feature "fuel_efficiency_mpg", and then find its maximum.

<span style="color: orange">Q5. What's the maximum fuel efficiency of cars from Asia?</span>
<span style="color: lightgreen">Ans.: 41.2 mpg</span>

In [12]:
np.max(datfile[datfile["origin"]=="Asia"].fuel_efficiency_mpg)

41.2

<span style="color: orange">Q6.

<span style="color: orange">1) Find the median value of the horsepower column in the dataset.</span><span style="color: lightgreen"> Ans.: 254.45</span>

<span style="color: orange">2) Next, calculate the most frequent value of the same horsepower column.</span><span style="color: lightgreen"> Ans.: 252.0. It appears 174 times.</span>

<span style="color: orange">3) Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.</span>

<span style="color: orange">4) Now, calculate the median value of horsepower once again.</span> <span style="color: lightgreen">Ans.: 254.23</span>

<span style="color: lightgreen">The mean value decreased a little bit.</span>

Drop the NaN entries of a column and compute the average.

In [4]:
filtered_HP = datfile["horsepower"].dropna()
np.average(filtered_HP)

np.float64(254.44601556505535)

Extract the most frequent value and how many times it appears.

In [5]:
mstfreq = filtered_HP.value_counts().index[0]
filtered_HP.value_counts().head(n=1)

horsepower
252.0    174
Name: count, dtype: int64

Fill the missing values in the "horsepower" column with the most frequent value from the previous step.

In [6]:
datfile["horsepower"] = datfile["horsepower"].fillna(mstfreq)

In [117]:
datfile["horsepower"].value_counts().head(n=1)

horsepower
152.0    850
Name: count, dtype: int64

Compute again the average.

In [16]:
np.average(datfile["horsepower"].values)

np.float64(254.2315)

<span style="color: orange">Q7. Sum of weights.</span>
<span style="color: lightgreen">Ans.: 0.369</span>

Now, from the rows corresponding to Asian cars, keep the columns "vehicle_weight" and "model_year".

In [7]:
asiancars = datfile[datfile["origin"]=="Asia"]
X = asiancars[["vehicle_weight", "model_year"]].head(n=7).values

In [8]:
Xm1 = np.linalg.inv(X.T @ X)
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
w = Xm1 @ X.T @ y
np.sum(w)

np.float64(0.3691969690492638)